version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nftix-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nftix
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: nftix-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/nftix?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key
      NODE_ENV: production
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongodb_data:
